### ISSUE TITLE
stage1_train is unavailable?

### ISSUE THREAD

**Issue by AVS7278** [dv-123/Lung_cancer#1]
In the dataset's google drive link, there is no stage1_train folder. Is it named as another folder?

**Comment by TushaRao** [comment]
It is the subset_0 folder

**Comment by dv-123** [comment]
Soory for inconvenience, i am a little busy now day, but i will try to take
out some time and document the repository properly.

Thankyou

**Comment by dv-123** [comment]
PS: It may take 3 or 4 weeks.

**Comment by TushaRao** [comment]
Can u tell me where can I find stage1_labels.csv file

**Comment by dv-123** [comment]
I am not sure because i am not touch with the repo. It was 2 years old B.
Tech. Project of mine. It will take some time for me also to figureout the
problems and solve them.

**Comment by AVS7278** [comment]
Thank you for your answer. I got the subset_0 folder.

**Comment by dv-123** [comment]
Mention not
